# Generated by Django 2.2.6 on 2020-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Reports',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='Team_lead',
            field=models.CharField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Rajan', 'Amitesh Rajan'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika'), ('Ajeet', 'Ajeet'), ('Shekhar', 'Shekhar')], default='Raktima Mitra', max_length=30),
        ),
    ]
